# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Import a ajouter
import sport
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime
import time


class Ui_MainWindow(object):

    # A Ajouter
    coach_sport = sport.Sport_Coach_Generator()
    page_serie = 0
    start_timer = time.time()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 353)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textDisplaySeries = QtWidgets.QTextBrowser(self.tab_2)
        self.textDisplaySeries.setGeometry(QtCore.QRect(10, 10, 441, 281))
        self.textDisplaySeries.setAutoFillBackground(False)
        self.textDisplaySeries.setObjectName("textDisplaySeries")

        # Initialise le texte du display avec les échauffements
        self.display_serie(0) #fa marf pas

        self.B_NextSerie = QtWidgets.QPushButton(self.tab_2)
        self.B_NextSerie.setEnabled(True)
        self.B_NextSerie.setGeometry(QtCore.QRect(380, 300, 75, 23))
        self.B_NextSerie.setCheckable(False)
        self.B_NextSerie.setAutoDefault(True)
        self.B_NextSerie.setDefault(False)
        self.B_NextSerie.setFlat(False)
        self.B_NextSerie.setObjectName("B_NextSerie")

        # A ajouter pour connecter le bouton next à son action
        self.B_NextSerie.clicked.connect(self.b_next_clicked)

        self.B_PreviousSerie = QtWidgets.QPushButton(self.tab_2)
        self.B_PreviousSerie.setGeometry(QtCore.QRect(290, 300, 75, 23))
        self.B_PreviousSerie.setObjectName("B_PreviousSerie")

        # A ajouter pour connecter le bouton previous à son action
        self.B_PreviousSerie.clicked.connect(self.b_previous_clicked)

        self.LCD_Minutes = QtWidgets.QLCDNumber(self.tab_2)
        self.LCD_Minutes.setGeometry(QtCore.QRect(10, 300, 64, 23))
        self.LCD_Minutes.setObjectName("LCD_Minutes")

        self.LCD_Secondes = QtWidgets.QLCDNumber(self.tab_2)
        self.LCD_Secondes.setGeometry(QtCore.QRect(80, 300, 64, 23))
        self.LCD_Secondes.setObjectName("LCD_Secondes")

        self.timer_du_timer = QTimer()
        self.timer_du_timer.timeout.connect(self.display_timer)
        self.timer_du_timer.start(1000)


        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        


    # Bouton Next pour afficher la série suivante
    def b_next_clicked(self):
        if self.page_serie < len(self.coach_sport.liste_affichage) - 1:
            self.page_serie += 1
            self.display_serie(self.page_serie)
    
    # Bouton previous pour revenir à la série précédente
    def b_previous_clicked(self):
        if self.page_serie > 0:
            self.page_serie -= 1
            self.display_serie(self.page_serie)

    def display_serie(self, indice_serie):
        # Clear l'affichage du GUI
        self.textDisplaySeries.clear()
        #Centre le texte, et faut le faire avant de print le texte
        self.textDisplaySeries.setAlignment(QtCore.Qt.AlignCenter)

        # Récupère la série correspondante au n° de la page
        text_list = self.coach_sport.liste_affichage[self.page_serie]
        
        # Affiche la série sur le GUI
        text = ""
        for i in text_list:
            self.textDisplaySeries.insertPlainText(i)

    def display_timer(self):
        currentTime = time.time()
        time_difference = int(currentTime - self.start_timer)
        minutes = time_difference // 60
        secondes = time_difference % 60
        self.LCD_Minutes.display(minutes)
        self.LCD_Secondes.display(secondes)
        




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sport Coach"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Menu"))
        self.textDisplaySeries.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.B_NextSerie.setText(_translate("MainWindow", "Next !"))
        self.B_PreviousSerie.setText(_translate("MainWindow", "Previous"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Séries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
