# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sport
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    coach_sport = sport.Sport_Coach_Generator()
    page_serie = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 353)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.B_NextSerie = QtWidgets.QPushButton(self.tab)
        self.B_NextSerie.setEnabled(True)
        self.B_NextSerie.setGeometry(QtCore.QRect(380, 300, 75, 23))
        self.B_NextSerie.setCheckable(False)
        self.B_NextSerie.setAutoDefault(True)
        self.B_NextSerie.setDefault(False)
        self.B_NextSerie.setFlat(False)
        self.B_NextSerie.setObjectName("B_NextSerie")

        # A ajouter pour connecter le bouton next à son action
        self.B_NextSerie.clicked.connect(self.b_next_clicked)

        self.textDisplaySeries = QtWidgets.QTextBrowser(self.tab)
        self.textDisplaySeries.setGeometry(QtCore.QRect(10, 10, 441, 281))
        self.textDisplaySeries.setAutoFillBackground(False)
        self.textDisplaySeries.setAlignment(QtCore.Qt.AlignCenter)
        self.textDisplaySeries.setObjectName("textDisplaySeries")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Bouton Next pour afficher la série suivante
    def b_next_clicked(self):
        self.page_serie += 1
        self.display_serie(self.page_serie)
    
    # Bouton previous pour revenir à la série précédente
    def b_previous_clicked(self):
        self.page_serie -= 1
        self.display_serie(self.page_serie)

    def display_serie(self, indice_serie):
        # Clear l'affichage du GUI
        self.textDisplaySeries.clear()
        #Centre le texte, et faut le faire avant de print le texte
        self.textDisplaySeries.setAlignment(QtCore.Qt.AlignCenter)

        # Récupère la série correspondante au n° de la page
        text_list = self.coach_sport.liste_affichage[self.page_serie]
        
        # Affiche la série sur le GUI
        text = ""
        for i in text_list:
            self.textDisplaySeries.insertPlainText(i)

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sport Coach"))
        self.B_NextSerie.setText(_translate("MainWindow", "Next !"))
        self.textDisplaySeries.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
