# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 353)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 471, 361))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Label_bienvenue = QtWidgets.QLabel(self.tab)
        self.Label_bienvenue.setGeometry(QtCore.QRect(160, 50, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_bienvenue.setFont(font)
        self.Label_bienvenue.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_bienvenue.setObjectName("Label_bienvenue")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textDisplaySeries = QtWidgets.QTextBrowser(self.tab_2)
        self.textDisplaySeries.setGeometry(QtCore.QRect(10, 10, 441, 281))
        self.textDisplaySeries.setAutoFillBackground(False)
        self.textDisplaySeries.setObjectName("textDisplaySeries")
        self.B_NextSerie = QtWidgets.QPushButton(self.tab_2)
        self.B_NextSerie.setEnabled(True)
        self.B_NextSerie.setGeometry(QtCore.QRect(377, 300, 75, 23))
        self.B_NextSerie.setCheckable(False)
        self.B_NextSerie.setAutoDefault(True)
        self.B_NextSerie.setDefault(False)
        self.B_NextSerie.setFlat(False)
        self.B_NextSerie.setObjectName("B_NextSerie")
        self.B_PreviousSerie = QtWidgets.QPushButton(self.tab_2)
        self.B_PreviousSerie.setEnabled(True)
        self.B_PreviousSerie.setGeometry(QtCore.QRect(290, 300, 75, 23))
        self.B_PreviousSerie.setObjectName("B_PreviousSerie")
        self.LCD_Minutes = QtWidgets.QLCDNumber(self.tab_2)
        self.LCD_Minutes.setGeometry(QtCore.QRect(10, 300, 64, 23))
        self.LCD_Minutes.setObjectName("LCD_Minutes")
        self.LCD_Secondes = QtWidgets.QLCDNumber(self.tab_2)
        self.LCD_Secondes.setGeometry(QtCore.QRect(80, 300, 64, 23))
        self.LCD_Secondes.setObjectName("LCD_Secondes")
        self.B_SeriePret = QtWidgets.QPushButton(self.tab_2)
        self.B_SeriePret.setGeometry(QtCore.QRect(193, 145, 75, 23))
        self.B_SeriePret.setObjectName("B_SeriePret")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.tableHistorique = QtWidgets.QTableWidget(self.tab_3)
        self.tableHistorique.setGeometry(QtCore.QRect(10, 10, 441, 311))
        self.tableHistorique.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHistorique.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableHistorique.setAutoScroll(False)
        self.tableHistorique.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistorique.setDragDropOverwriteMode(False)
        self.tableHistorique.setAlternatingRowColors(True)
        self.tableHistorique.setCornerButtonEnabled(False)
        self.tableHistorique.setRowCount(1)
        self.tableHistorique.setColumnCount(3)
        self.tableHistorique.setObjectName("tableHistorique")
        self.tableHistorique.horizontalHeader().setVisible(False)
        self.tableHistorique.horizontalHeader().setCascadingSectionResizes(False)
        self.tableHistorique.horizontalHeader().setDefaultSectionSize(210)
        self.tableHistorique.horizontalHeader().setHighlightSections(True)
        self.tableHistorique.horizontalHeader().setSortIndicatorShown(False)
        self.tableHistorique.horizontalHeader().setStretchLastSection(True)
        self.tableHistorique.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sport Coach"))
        self.Label_bienvenue.setText(_translate("MainWindow", "Coach Sport"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Menu"))
        self.textDisplaySeries.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.B_NextSerie.setText(_translate("MainWindow", "Next !"))
        self.B_PreviousSerie.setText(_translate("MainWindow", "Previous"))
        self.B_SeriePret.setText(_translate("MainWindow", "Je suis Prêt !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Séries"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Historique"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
